#!/usr/bin/env python3
"""Daily Tech Pulse — fetch trending repos, analyze, commit report, PR, merge, issue."""

from __future__ import annotations

import os
import re
import sys
from datetime import datetime, timedelta, timezone
from pathlib import Path

import requests
from github import Github, GithubException
from google import genai

BANGKOK = timezone(timedelta(hours=7))
ROOT = Path(__file__).resolve().parent.parent
README_PATH = ROOT / "README.md"
REPORTS_DIR = ROOT / "reports"

DAILY_TOKEN = os.environ.get("DAILY_TOKEN", "")
GITHUB_TOKEN = os.environ.get("GITHUB_TOKEN", "")
GEMINI_API_KEY = os.environ.get("GEMINI_API_KEY", "")
REPO_FULL_NAME = os.environ.get("GITHUB_REPOSITORY", "")


def get_github_token() -> str:
    token = DAILY_TOKEN or GITHUB_TOKEN
    if not token:
        print(
            "ERROR: No GitHub token found.\n"
            "Add repository secret DAILY_TOKEN (scopes: repo, workflow) at:\n"
            "  Settings → Secrets and variables → Actions → New repository secret",
            file=sys.stderr,
        )
        sys.exit(1)
    if not DAILY_TOKEN:
        print(
            "ℹ️  Using GITHUB_TOKEN — commits appear as github-actions[bot]. "
            "Add DAILY_TOKEN for contributions on your profile."
        )
    return token

TRENDING_LIMIT = 10
GEMINI_MODEL = os.environ.get("GEMINI_MODEL", "gemini-2.0-flash")


def today_bangkok() -> datetime:
    return datetime.now(BANGKOK)


def report_date_str() -> str:
    return today_bangkok().strftime("%Y-%m-%d")


def fetch_trending_repos(limit: int = TRENDING_LIMIT) -> list[dict]:
    since = (datetime.now(timezone.utc) - timedelta(days=7)).strftime("%Y-%m-%d")
    url = "https://api.github.com/search/repositories"
    params = {
        "q": f"created:>{since} stars:>50",
        "sort": "stars",
        "order": "desc",
        "per_page": limit,
    }
    headers = {"Accept": "application/vnd.github+json"}
    token = DAILY_TOKEN or GITHUB_TOKEN
    if token:
        headers["Authorization"] = f"Bearer {token}"

    response = requests.get(url, params=params, headers=headers, timeout=30)
    response.raise_for_status()
    return response.json().get("items", [])


def repo_summary_block(repos: list[dict]) -> str:
    lines = []
    for i, repo in enumerate(repos, 1):
        desc = (repo.get("description") or "No description").strip()
        lines.append(
            f"{i}. **[{repo['full_name']}]({repo['html_url']})** — "
            f"⭐ {repo['stargazers_count']:,} | {repo.get('language') or 'N/A'}\n"
            f"   {desc}"
        )
    return "\n\n".join(lines)


def generate_ai_digest(repos: list[dict]) -> str:
    if not GEMINI_API_KEY:
        return (
            "_AI digest unavailable — add `GEMINI_API_KEY` to repository secrets "
            "for Gemini-powered analysis._"
        )

    repo_lines = "\n".join(
        f"- {r['full_name']}: {r.get('description') or 'N/A'} "
        f"({r['stargazers_count']} stars, {r.get('language') or 'unknown'})"
        for r in repos
    )
    prompt = f"""You are a tech analyst writing a daily GitHub trending digest.
Today's date: {report_date_str()}

Trending repositories (last 7 days):
{repo_lines}

Write a concise Markdown section (in English) with:
1. A 2-sentence executive summary of today's trends
2. "Top Picks" — brief insight on the 3 most interesting repos (1-2 sentences each)
3. "Trend Watch" — one paragraph on patterns (languages, domains, tools)

Keep it under 400 words. Use ### headings. No preamble."""

    client = genai.Client(api_key=GEMINI_API_KEY)
    response = client.models.generate_content(
        model=GEMINI_MODEL,
        contents=prompt,
    )
    return response.text.strip()


def build_report(repos: list[dict], ai_digest: str) -> str:
    date = report_date_str()
    summary = repo_summary_block(repos)
    return f"""# 📊 Daily Tech Pulse — {date}

> Auto-generated report of GitHub's hottest new repositories.

---

## 🧠 AI Digest

{ai_digest}

---

## 📡 Trending Repositories (last 7 days)

{summary}

---

*Generated by [Daily Tech Pulse](https://github.com/{REPO_FULL_NAME}) 🤖*
"""


def build_readme_snippet(report_filename: str, repos: list[dict]) -> str:
    date = report_date_str()
    top = repos[0] if repos else None
    top_line = (
        f"Top repo: **[{top['full_name']}]({top['html_url']})** "
        f"(⭐ {top['stargazers_count']:,})"
        if top
        else "No trending repos found today."
    )
    return f"""## 📊 Latest Report: [{date}](reports/{report_filename})

{top_line}

[Read full report →](reports/{report_filename})"""


def update_readme(snippet: str) -> str:
    content = README_PATH.read_text(encoding="utf-8")
    pattern = re.compile(
        r"<!-- LATEST_REPORT_START -->.*?<!-- LATEST_REPORT_END -->",
        re.DOTALL,
    )
    replacement = (
        f"<!-- LATEST_REPORT_START -->\n{snippet}\n<!-- LATEST_REPORT_END -->"
    )
    if not pattern.search(content):
        raise RuntimeError("README markers not found")
    return pattern.sub(replacement, content)


def create_issue_body(repos: list[dict], ai_digest: str) -> str:
    date = report_date_str()
    highlights = "\n".join(
        f"- [{r['full_name']}]({r['html_url']}) — ⭐ {r['stargazers_count']:,}"
        for r in repos[:5]
    )
    digest_preview = ai_digest[:500] + ("..." if len(ai_digest) > 500 else "")
    return f"""## 📋 Daily Highlights — {date}

### 🔥 Top Repos
{highlights}

### 🧠 AI Summary
{digest_preview}

---
📄 Full report: `reports/{date}.md`
🤖 Auto-generated by Daily Tech Pulse
"""


def report_on_main(repo, report_rel: str) -> bool:
    try:
        repo.get_contents(report_rel, ref=repo.default_branch)
        return True
    except GithubException as exc:
        if exc.status == 404:
            return False
        raise


def find_open_pr(repo, branch_name: str):
    pulls = repo.get_pulls(state="open", head=f"{repo.owner.login}:{branch_name}")
    return next(iter(pulls), None)


def finish_report(repo, branch_name: str, date: str, report_filename: str, repos: list, ai_digest: str) -> None:
    pr = find_open_pr(repo, branch_name)
    if pr is None:
        print("🔀 Opening pull request...")
        pr = repo.create_pull(
            title=f"📊 Daily Report: {date}",
            body=f"Automated daily tech digest for **{date}**.\n\n"
            f"- Report: `reports/{report_filename}`\n"
            f"- Trending repos analyzed: {len(repos)}",
            head=branch_name,
            base=repo.default_branch,
        )
    else:
        print(f"🔀 Found existing PR #{pr.number}")

    if pr.is_merged():
        print(f"✅ PR #{pr.number} already merged")
    else:
        print("✅ Merging pull request...")
        pr.merge(merge_method="squash", commit_title=f"📊 Daily report {date} (#{pr.number})")

    issue_title = f"📋 Daily Highlights: {date}"
    existing = list(repo.get_issues(state="open", creator=repo.owner.login))
    if any(i.title == issue_title for i in existing):
        print("📋 Daily issue already exists — skipping")
    else:
        print("📋 Creating daily issue...")
        try:
            repo.create_issue(
                title=issue_title,
                body=create_issue_body(repos, ai_digest),
                labels=["daily-digest", "automated"],
            )
        except GithubException:
            repo.create_issue(title=issue_title, body=create_issue_body(repos, ai_digest))


def run() -> None:
    token = get_github_token()
    if not REPO_FULL_NAME:
        print("ERROR: GITHUB_REPOSITORY env var is required", file=sys.stderr)
        sys.exit(1)

    date = report_date_str()
    branch_name = f"report/{date}"
    report_filename = f"{date}.md"
    report_path = REPORTS_DIR / report_filename
    report_rel = report_path.relative_to(ROOT).as_posix()

    gh = Github(token)
    repo = gh.get_repo(REPO_FULL_NAME)

    if report_on_main(repo, report_rel):
        print(f"✅ Report for {date} already on {repo.default_branch} — nothing to do")
        return

    print(f"📡 Fetching trending repos for {date}...")
    repos = fetch_trending_repos()
    print(f"   Found {len(repos)} repositories")

    print("🧠 Generating AI digest...")
    ai_digest = generate_ai_digest(repos)

    branch_exists = False
    try:
        repo.get_branch(branch_name)
        branch_exists = True
    except GithubException as exc:
        if exc.status != 404:
            raise

    if branch_exists:
        print(f"🌿 Resuming incomplete report on {branch_name}...")
        finish_report(repo, branch_name, date, report_filename, repos, ai_digest)
        print(f"🎉 Done! Report published for {date}")
        return

    report_content = build_report(repos, ai_digest)
    readme_content = update_readme(build_readme_snippet(report_filename, repos))
    main_branch = repo.get_branch(repo.default_branch)
    base_sha = main_branch.commit.sha

    print(f"🌿 Creating branch {branch_name}...")
    repo.create_git_ref(ref=f"refs/heads/{branch_name}", sha=base_sha)

    commit_msg = f"📊 Daily report {date}"
    print("💾 Committing report and README...")
    repo.create_file(
        path=report_rel,
        message=commit_msg,
        content=report_content,
        branch=branch_name,
    )

    readme_file = repo.get_contents("README.md", ref=branch_name)
    repo.update_file(
        path=readme_file.path,
        message="📝 Update README with latest report",
        content=readme_content,
        sha=readme_file.sha,
        branch=branch_name,
    )

    finish_report(repo, branch_name, date, report_filename, repos, ai_digest)
    print(f"🎉 Done! Report published for {date}")


if __name__ == "__main__":
    run()
