#!/usr/bin/env python3
"""Daily Tech Pulse — fetch trending repos, analyze, commit report, PR, merge, issue."""

from __future__ import annotations

import os
import re
import sys
from datetime import datetime, timedelta, timezone
from pathlib import Path

import requests
from anthropic import Anthropic
from github import Github, GithubException

BANGKOK = timezone(timedelta(hours=7))
ROOT = Path(__file__).resolve().parent.parent
README_PATH = ROOT / "README.md"
REPORTS_DIR = ROOT / "reports"

PAT_TOKEN = os.environ.get("PAT_TOKEN", "")
ANTHROPIC_API_KEY = os.environ.get("ANTHROPIC_API_KEY", "")
REPO_FULL_NAME = os.environ.get("GITHUB_REPOSITORY", "")

TRENDING_LIMIT = 10
AI_MODEL = "claude-sonnet-4-20250514"


def today_bangkok() -> datetime:
    return datetime.now(BANGKOK)


def report_date_str() -> str:
    return today_bangkok().strftime("%Y-%m-%d")


def fetch_trending_repos(limit: int = TRENDING_LIMIT) -> list[dict]:
    since = (datetime.now(timezone.utc) - timedelta(days=7)).strftime("%Y-%m-%d")
    url = "https://api.github.com/search/repositories"
    params = {
        "q": f"created:>{since} stars:>50",
        "sort": "stars",
        "order": "desc",
        "per_page": limit,
    }
    headers = {"Accept": "application/vnd.github+json"}
    if PAT_TOKEN:
        headers["Authorization"] = f"Bearer {PAT_TOKEN}"

    response = requests.get(url, params=params, headers=headers, timeout=30)
    response.raise_for_status()
    return response.json().get("items", [])


def repo_summary_block(repos: list[dict]) -> str:
    lines = []
    for i, repo in enumerate(repos, 1):
        desc = (repo.get("description") or "No description").strip()
        lines.append(
            f"{i}. **[{repo['full_name']}]({repo['html_url']})** — "
            f"⭐ {repo['stargazers_count']:,} | {repo.get('language') or 'N/A'}\n"
            f"   {desc}"
        )
    return "\n\n".join(lines)


def generate_ai_digest(repos: list[dict]) -> str:
    if not ANTHROPIC_API_KEY:
        return (
            "_AI digest unavailable — add `ANTHROPIC_API_KEY` to repository secrets "
            "for Claude-powered analysis._"
        )

    repo_lines = "\n".join(
        f"- {r['full_name']}: {r.get('description') or 'N/A'} "
        f"({r['stargazers_count']} stars, {r.get('language') or 'unknown'})"
        for r in repos
    )
    prompt = f"""You are a tech analyst writing a daily GitHub trending digest.
Today's date: {report_date_str()}

Trending repositories (last 7 days):
{repo_lines}

Write a concise Markdown section (in English) with:
1. A 2-sentence executive summary of today's trends
2. "Top Picks" — brief insight on the 3 most interesting repos (1-2 sentences each)
3. "Trend Watch" — one paragraph on patterns (languages, domains, tools)

Keep it under 400 words. Use ### headings. No preamble."""

    client = Anthropic(api_key=ANTHROPIC_API_KEY)
    message = client.messages.create(
        model=AI_MODEL,
        max_tokens=1024,
        messages=[{"role": "user", "content": prompt}],
    )
    return message.content[0].text.strip()


def build_report(repos: list[dict], ai_digest: str) -> str:
    date = report_date_str()
    summary = repo_summary_block(repos)
    return f"""# 📊 Daily Tech Pulse — {date}

> Auto-generated report of GitHub's hottest new repositories.

---

## 🧠 AI Digest

{ai_digest}

---

## 📡 Trending Repositories (last 7 days)

{summary}

---

*Generated by [Daily Tech Pulse](https://github.com/{REPO_FULL_NAME}) 🤖*
"""


def build_readme_snippet(report_filename: str, repos: list[dict]) -> str:
    date = report_date_str()
    top = repos[0] if repos else None
    top_line = (
        f"Top repo: **[{top['full_name']}]({top['html_url']})** "
        f"(⭐ {top['stargazers_count']:,})"
        if top
        else "No trending repos found today."
    )
    return f"""## 📊 Latest Report: [{date}](reports/{report_filename})

{top_line}

[Read full report →](reports/{report_filename})"""


def update_readme(snippet: str) -> str:
    content = README_PATH.read_text(encoding="utf-8")
    pattern = re.compile(
        r"<!-- LATEST_REPORT_START -->.*?<!-- LATEST_REPORT_END -->",
        re.DOTALL,
    )
    replacement = (
        f"<!-- LATEST_REPORT_START -->\n{snippet}\n<!-- LATEST_REPORT_END -->"
    )
    if not pattern.search(content):
        raise RuntimeError("README markers not found")
    return pattern.sub(replacement, content)


def create_issue_body(repos: list[dict], ai_digest: str) -> str:
    date = report_date_str()
    highlights = "\n".join(
        f"- [{r['full_name']}]({r['html_url']}) — ⭐ {r['stargazers_count']:,}"
        for r in repos[:5]
    )
    digest_preview = ai_digest[:500] + ("..." if len(ai_digest) > 500 else "")
    return f"""## 📋 Daily Highlights — {date}

### 🔥 Top Repos
{highlights}

### 🧠 AI Summary
{digest_preview}

---
📄 Full report: `reports/{date}.md`
🤖 Auto-generated by Daily Tech Pulse
"""


def run() -> None:
    if not PAT_TOKEN:
        print("ERROR: PAT_TOKEN secret is required", file=sys.stderr)
        sys.exit(1)
    if not REPO_FULL_NAME:
        print("ERROR: GITHUB_REPOSITORY env var is required", file=sys.stderr)
        sys.exit(1)

    date = report_date_str()
    branch_name = f"report/{date}"
    report_filename = f"{date}.md"
    report_path = REPORTS_DIR / report_filename

    print(f"📡 Fetching trending repos for {date}...")
    repos = fetch_trending_repos()
    print(f"   Found {len(repos)} repositories")

    print("🧠 Generating AI digest...")
    ai_digest = generate_ai_digest(repos)

    report_content = build_report(repos, ai_digest)
    readme_content = update_readme(build_readme_snippet(report_filename, repos))

    gh = Github(PAT_TOKEN)
    repo = gh.get_repo(REPO_FULL_NAME)
    main_branch = repo.get_branch(repo.default_branch)
    base_sha = main_branch.commit.sha

    # Skip if today's report branch already exists
    try:
        repo.get_branch(branch_name)
        print(f"⚠️  Branch {branch_name} already exists — skipping")
        sys.exit(0)
    except GithubException as exc:
        if exc.status != 404:
            raise

    print(f"🌿 Creating branch {branch_name}...")
    repo.create_git_ref(ref=f"refs/heads/{branch_name}", sha=base_sha)

    report_rel = report_path.relative_to(ROOT).as_posix()
    commit_msg = f"📊 Daily report {date}"

    print("💾 Committing report and README...")
    repo.create_file(
        path=report_rel,
        message=commit_msg,
        content=report_content,
        branch=branch_name,
    )

    readme_file = repo.get_contents("README.md", ref=branch_name)
    repo.update_file(
        path=readme_file.path,
        message="📝 Update README with latest report",
        content=readme_content,
        sha=readme_file.sha,
        branch=branch_name,
    )

    print("🔀 Opening pull request...")
    pr = repo.create_pull(
        title=f"📊 Daily Report: {date}",
        body=f"Automated daily tech digest for **{date}**.\n\n"
        f"- Report: `reports/{report_filename}`\n"
        f"- Trending repos analyzed: {len(repos)}",
        head=branch_name,
        base=repo.default_branch,
    )

    print("✅ Merging pull request...")
    pr.merge(merge_method="squash", commit_title=f"📊 Daily report {date} (#{pr.number})")

    print("📋 Creating daily issue...")
    try:
        repo.create_issue(
            title=f"📋 Daily Highlights: {date}",
            body=create_issue_body(repos, ai_digest),
            labels=["daily-digest", "automated"],
        )
    except GithubException:
        repo.create_issue(
            title=f"📋 Daily Highlights: {date}",
            body=create_issue_body(repos, ai_digest),
        )

    print(f"🎉 Done! Report published for {date}")


if __name__ == "__main__":
    run()
